CLI improvements
eguiraud/root-readspeed pull request #15
Opened 2022-07-21 12:09 UTC by dkpoult

This PR adds some improvements to how the CLI handles arguments.
- Invalid flags are now detected and make the execution stop (even in file/tree/branch lists)
- Adds various test cases to ensure the new functionality and old functionality both work

2022-07-26 23:55 UTC, eguiraud requested changes
Thanks @dkpoult ! Is there a test for the case mentioned in #10 , namely `--branches x --notanoption`? I did not see one.

Some more comments below.

2022-07-26 23:55 UTC, eguiraud commented on src/ReadSpeedCLI.cxx
> +   if (args.size() < 2 || (args.size() == 2 && (args[1].compare("--help") == 0 || args[1].compare("-h") == 0))) {
please use `str1 == str2` instead of `str1.compare(str2) == 0`, for readability

2022-07-26 23:55 UTC, eguiraud commented on src/ReadSpeedCLI.cxx
> +      args.push_back(std::string(argv[i]));
less noisy and avoids a temporary: `args.emplace_back(argv[i])`

2022-07-26 23:55 UTC, eguiraud commented on src/ReadSpeedCLI.cxx
> +Args ReadSpeed::ParseArgs(std::vector<std::string> args)
avoid a copy with `const std::vector<std::string> &`

2022-07-26 23:55 UTC, eguiraud commented on src/ReadSpeedCLI.cxx
> +      auto arg = args[i];
avoid a copy with `const auto &arg = args[i];`

2022-07-26 23:55 UTC, eguiraud commented on test/tests.cpp
> +      CHECK_MESSAGE(!parsedArgs.fShouldRun, "Programme running when using help argument");
Not really a problem, but in ROOT in general we use the US spelling "program"

2022-07-28 11:48 UTC, dkpoult commented
> Is there a test for the case mentioned in #10 , namely `--branches x --notanoption`? I did not see one.

I've added one now, thanks for the catch!

2022-08-01 18:03 UTC, eguiraud requested changes
Great, thanks! Just two last minor comments :)

2022-08-01 18:03 UTC, eguiraud commented on src/ReadSpeedCLI.cxx
> +      } else if (arg.compare(0, 1, "-") == 0) {
more readable:

```suggestion
      } else if (arg[0] == '-') {
```

2022-08-01 18:03 UTC, eguiraud commented on src/ReadSpeedCLI.cxx
> +      const auto &arg = args[i];
can this just be:
```suggestion
   for (const auto &arg : args) {
```
?

2022-08-02 12:25 UTC, dkpoult commented on src/ReadSpeedCLI.cxx
> +      const auto &arg = args[i];
It needs to skip the first arg which would be "root-readspeed" or something similar so using a ranged-based loop is a bit more convoluted

2022-08-02 13:28 UTC, eguiraud commented on src/ReadSpeedCLI.cxx
> +      const auto &arg = args[i];
ah right, fair enough

2022-08-02 13:29 UTC, eguiraud approved these changes

2022-08-02 13:29 UTC, merged